"""Generate 100 bilingual questions (English + Vietnamese) with Markdown and LaTeX."""
import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.worksheet.datavalidation import DataValidation

BILINGUAL_QUESTIONS = [
    # === Easy Finance Questions (1-10) ===
    {
        "title": "Simple Interest Calculation",
        "title_vi": "Tính lãi suất đơn",
        "question": "You invest **$1,000** at an interest rate of **5%** per year. How much interest will you earn in **2 years**?\n\n$$I = P \\times r \\times t$$",
        "question_vi": "Bạn đầu tư **$1.000** với lãi suất **5%** mỗi năm. Bạn sẽ kiếm được bao nhiêu tiền lãi trong **2 năm**?\n\n$$I = P \\times r \\times t$$",
        "answer": "100",
        "explanation": "Using the simple interest formula:\n\n$$I = 1000 \\times 0.05 \\times 2 = 100$$\n\nYou will earn **$100** in interest over 2 years.",
        "explanation_vi": "Sử dụng công thức lãi suất đơn:\n\n$$I = 1000 \\times 0,05 \\times 2 = 100$$\n\nBạn sẽ kiếm được **$100** tiền lãi trong 2 năm.",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Percentage Discount",
        "title_vi": "Tính giảm giá theo phần trăm",
        "question": "A store is having a **20% off** sale. If a shirt costs **$50**, what is the sale price?",
        "question_vi": "Một cửa hàng có chương trình **giảm 20%**. Nếu một chiếc áo có giá **$50**, giá bán là bao nhiêu?",
        "answer": "40",
        "explanation": "$$\\text{Sale Price} = 50 \\times (1 - 0.20) = 50 \\times 0.80 = 40$$",
        "explanation_vi": "$$\\text{Gia ban} = 50 \\times (1 - 0,20) = 50 \\times 0,80 = 40$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Profit Calculation",
        "title_vi": "Tính lợi nhuận",
        "question": "You buy a book for **$12** and sell it for **$18**. What is your profit?",
        "question_vi": "Bạn mua một cuốn sách với giá **$12** và bán với giá **$18**. Lợi nhuận của bạn là bao nhiêu?",
        "answer": "6",
        "explanation": "$$\\text{Profit} = 18 - 12 = 6$$",
        "explanation_vi": "$$\\text{Loi nhuan} = 18 - 12 = 6$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Currency Exchange",
        "title_vi": "Tính tỷ giá hối đoái",
        "question": "Exchange rate: **1 USD = 24,000 VND**. How many VND for **$50 USD**?",
        "question_vi": "Tỷ giá: **1 USD = 24.000 VND**. Bạn nhận bao nhiêu VND cho **$50 USD**?",
        "answer": "1200000",
        "explanation": "$$50 \\times 24000 = 1,200,000$$",
        "explanation_vi": "$$50 \\times 24.000 = 1.200.000$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Budget Allocation",
        "title_vi": "Phân bổ ngân sách",
        "question": "Monthly income: **3,000,000 VND**. Expenses: **40%** rent, **25%** food, **15%** utilities. Savings?",
        "question_vi": "Thu nhập tháng: **3.000.000 VND**. Chi tiêu: **40%** thuê nhà, **25%** thức ăn, **15%** tiện ích. Tiết kiệm?",
        "answer": "600000",
        "explanation": "$$100\\% - (40\\% + 25\\% + 15\\%) = 20\\%$$\n$$3,000,000 \\times 0.20 = 600,000$$",
        "explanation_vi": "$$100\\% - (40\\% + 25\\% + 15\\%) = 20\\%$$\n$$3.000.000 \\times 0,20 = 600.000$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Compound Interest Year 1",
        "title_vi": "Lãi kép sau 1 năm",
        "question": "Deposit: **$1,000** at **10% annual compound interest**. Balance after **1 year**?",
        "question_vi": "Gửi: **$1.000** lãi kép **10% mỗi năm**. Số dư sau **1 năm**?",
        "answer": "1100",
        "explanation": "$$A = 1000 \\times (1.10)^1 = 1,100$$",
        "explanation_vi": "$$A = 1.000 \\times (1,10)^1 = 1.100$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Break-even Analysis",
        "title_vi": "Phân tích điểm hòa vốn",
        "question": "Lemonade stand: fixed cost **$100**, price **$2** per unit. Units to break even?",
        "question_vi": "Quầy nước chanh: chi phí cố định **$100**, giá **$2** mỗi cốc. Bao nhiêu cốc để hòa vốn?",
        "answer": "50",
        "explanation": "$$\\text{Break-even} = \\frac{100}{2} = 50$$",
        "explanation_vi": "$$\\text{Hoa von} = \\frac{100}{2} = 50$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Average Expense",
        "title_vi": "Chi tiêu trung bình",
        "question": "Monthly expenses: **$500, $600, $400**. Average?",
        "question_vi": "Chi tiêu hàng tháng: **$500, $600, $400**. Bình quân?",
        "answer": "500",
        "explanation": "$$\\frac{500 + 600 + 400}{3} = \\frac{1500}{3} = 500$$",
        "explanation_vi": "$$\\frac{500 + 600 + 400}{3} = \\frac{1500}{3} = 500$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Markup Pricing",
        "title_vi": "Tính giá bán với lợi nhuận",
        "question": "Buy: **$100**, want **50% markup**. Selling price?",
        "question_vi": "Mua: **$100**, muốn **lợi nhuận 50%**. Giá bán?",
        "answer": "150",
        "explanation": "$$100 \\times (1 + 0.50) = 150$$",
        "explanation_vi": "$$100 \\times (1 + 0,50) = 150$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Restaurant Tip",
        "title_vi": "Tiền boa nhà hàng",
        "question": "Bill: **$80**. Tip **15%**. How much tip?",
        "question_vi": "Hóa đơn: **$80**. Boa **15%**. Bao nhiêu tiền boa?",
        "answer": "12",
        "explanation": "$$80 \\times 0.15 = 12$$",
        "explanation_vi": "$$80 \\times 0,15 = 12$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },

    # === Medium Business Questions (11-30) ===
    {
        "title": "ROI Calculation",
        "title_vi": "Tính lợi suất đầu tư (ROI)",
        "question": "Investment: **$5,000**, Profit: **$1,000**. ROI?\n\n$$ROI = \\frac{\\text{Profit}}{\\text{Investment}} \\times 100\\%$$",
        "question_vi": "Đầu tư: **$5.000**, Lợi nhuận: **$1.000**. ROI?\n\n$$ROI = \\frac{\\text{Loi nhuan}}{\\text{Dau tu}} \\times 100\\%$$",
        "answer": "20",
        "explanation": "$$ROI = \\frac{1000}{5000} \\times 100\\% = 20\\%$$",
        "explanation_vi": "$$ROI = \\frac{1000}{5000} \\times 100\\% = 20\\%$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Debt-to-Income Ratio",
        "title_vi": "Tỷ lệ nợ trên thu nhập",
        "question": "Annual income: **$60,000**. Annual debt payments: **$12,000**. Ratio?",
        "question_vi": "Thu nhập hàng năm: **$60.000**. Thanh toán nợ hàng năm: **$12.000**. Tỷ lệ?",
        "answer": "20",
        "explanation": "$$\\frac{12000}{60000} \\times 100\\% = 20\\%$$",
        "explanation_vi": "$$\\frac{12000}{60000} \\times 100\\% = 20\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Revenue from Sales",
        "title_vi": "Tính doanh thu",
        "question": "Sold **150 units** at **$25** per unit. Revenue?",
        "question_vi": "Bán **150 cái** với giá **$25** mỗi cái. Doanh thu?",
        "answer": "3750",
        "explanation": "$$\\text{Revenue} = 150 \\times 25 = 3,750$$",
        "explanation_vi": "$$\\text{Doanh thu} = 150 \\times 25 = 3.750$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Gross Profit Margin",
        "title_vi": "Tính tỷ suất lợi nhuận gộp",
        "question": "Revenue: **$10,000**, Cost of Goods: **$6,000**. Gross margin %?",
        "question_vi": "Doanh thu: **$10.000**, Giá vốn: **$6.000**. Tỷ suất lợi nhuận gộp %?",
        "answer": "40",
        "explanation": "$$\\text{Margin} = \\frac{10000 - 6000}{10000} \\times 100\\% = 40\\%$$",
        "explanation_vi": "$$\\text{Margin} = \\frac{10000 - 6000}{10000} \\times 100\\% = 40\\%$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Inventory Turnover",
        "title_vi": "Tính vòng quay hàng tồn kho",
        "question": "COGS: **$50,000**, Average inventory: **$10,000**. Turnover?",
        "question_vi": "Giá vốn: **$50.000**, Hàng tồn kho trung bình: **$10.000**. Vòng quay?",
        "answer": "5",
        "explanation": "$$\\text{Turnover} = \\frac{50000}{10000} = 5$$",
        "explanation_vi": "$$\\text{Vong quay} = \\frac{50000}{10000} = 5$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Cash Flow Calculation",
        "title_vi": "Tính dòng tiền mặt",
        "question": "Revenue: **$50,000**, Expenses: **$30,000**, Taxes: **$5,000**. Cash flow?",
        "question_vi": "Doanh thu: **$50.000**, Chi phí: **$30.000**, Thuế: **$5.000**. Dòng tiền?",
        "answer": "15000",
        "explanation": "$$\\text{Cash Flow} = 50000 - 30000 - 5000 = 15,000$$",
        "explanation_vi": "$$\\text{Dong tien} = 50000 - 30000 - 5000 = 15.000$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Price Elasticity",
        "title_vi": "Tính độ co giãn của giá",
        "question": "Price increase: **10%**, Quantity decrease: **5%**. Elasticity?\n\n$$E = \\frac{\\% \\text{ Change Qty}}{\\% \\text{ Change Price}}$$",
        "question_vi": "Tăng giá: **10%**, Giảm lượng: **5%**. Độ co giãn?\n\n$$E = \\frac{\\% \\text{ Thay doi SL}}{\\% \\text{ Thay doi Gia}}$$",
        "answer": "-0.5",
        "explanation": "$$E = \\frac{-5\\%}{10\\%} = -0.5$$",
        "explanation_vi": "$$E = \\frac{-5\\%}{10\\%} = -0,5$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Payback Period",
        "title_vi": "Thời gian hoàn vốn",
        "question": "Investment: **$10,000**, Annual return: **$2,500**. Payback period (years)?",
        "question_vi": "Đầu tư: **$10.000**, Thu nhập hàng năm: **$2.500**. Thời gian hoàn vốn (năm)?",
        "answer": "4",
        "explanation": "$$\\text{Period} = \\frac{10000}{2500} = 4 \\text{ years}$$",
        "explanation_vi": "$$\\text{Thoi gian} = \\frac{10000}{2500} = 4 \\text{ nam}$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Break-even Units",
        "title_vi": "Điểm hòa vốn (số lượng)",
        "question": "Fixed cost: **$5,000**, Contribution margin/unit: **$25**. Break-even units?",
        "question_vi": "Chi phí cố định: **$5.000**, Lợi nhuận biên/đơn vị: **$25**. Điểm hòa vốn?",
        "answer": "200",
        "explanation": "$$\\text{Units} = \\frac{5000}{25} = 200$$",
        "explanation_vi": "$$\\text{Don vi} = \\frac{5000}{25} = 200$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },

    # === Hard Finance Questions (31-45) ===
    {
        "title": "NPV Calculation",
        "title_vi": "Tính giá trị hiện tại ròng (NPV)",
        "question": "Initial investment: **$10,000**, CF: Year 1: **$6,000**, Year 2: **$5,000**, Year 3: **$4,000**. Discount rate: **10%**. NPV?",
        "question_vi": "Đầu tư ban đầu: **$10.000**, Dòng tiền: Năm 1: **$6.000**, Năm 2: **$5.000**, Năm 3: **$4.000**. Lãi suất chiết khấu: **10%**. NPV?",
        "answer": "2624.19",
        "explanation": "$$NPV = -10000 + \\frac{6000}{1.1} + \\frac{5000}{1.1^2} + \\frac{4000}{1.1^3}$$\n$$= -10000 + 5454.55 + 4132.23 + 3005.26 = 2,592.04$$",
        "explanation_vi": "$$NPV = -10000 + \\frac{6000}{1,1} + \\frac{5000}{1,1^2} + \\frac{4000}{1,1^3}$$\n$$= -10000 + 5454,55 + 4132,23 + 3005,26 = 2.592$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 3,
    },
    {
        "title": "Loan Payment PMT",
        "title_vi": "Tính thanh toán khoản vay",
        "question": "Loan: **$10,000** at **12% annual**. Monthly payment for **12 months**?",
        "question_vi": "Vay: **$10.000** lãi **12% hàng năm**. Thanh toán hàng tháng trong **12 tháng**?",
        "answer": "888.49",
        "explanation": "Using PMT formula with monthly rate 1%, 12 periods:\n$$M \\approx 888.49$$",
        "explanation_vi": "Sử dụng công thức PMT với lãi suất tháng 1%, 12 kỳ:\n$$M \\approx 888,49$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Future Value Compound",
        "title_vi": "Giá trị tương lai với lãi kép",
        "question": "Investment: **$5,000** at **8% annual** compounded **quarterly** for **3 years**. FV?",
        "question_vi": "Đầu tư: **$5.000** lãi **8% hàng năm** lãi kép **hàng quý** trong **3 năm**. FV?",
        "answer": "6326.59",
        "explanation": "$$FV = 5000\\left(1 + \\frac{0.08}{4}\\right)^{12} = 5000(1.02)^{12} \\approx 6,341.21$$",
        "explanation_vi": "$$FV = 5000\\left(1 + \\frac{0,08}{4}\\right)^{12} = 5000(1,02)^{12} \\approx 6.341,21$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "IRR Approximation",
        "title_vi": "Tính lãi suất hoàn vốn nội (IRR)",
        "question": "Project: Initial outlay **$1,000**, CF year 1: **$600**, CF year 2: **$500**. Approximate IRR?",
        "question_vi": "Dự án: Chi ban đầu **$1.000**, Dòng tiền năm 1: **$600**, Năm 2: **$500**. IRR xấp xỉ?",
        "answer": "13.6",
        "explanation": "Using trial-and-error or approximation, IRR ≈ **13.6%**",
        "explanation_vi": "Sử dụng phương pháp thử-sai hoặc xấp xỉ, IRR ≈ **13,6%**",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 3,
    },
    {
        "title": "Bond Yield Calculation",
        "title_vi": "Tính lợi suất trái phiếu",
        "question": "Bond: Face value **$1,000**, Coupon **5%**, Price **$950**. Current yield?",
        "question_vi": "Trái phiếu: Mệnh giá **$1.000**, Lãi suất **5%**, Giá **$950**. Lợi suất hiện tại?",
        "answer": "5.26",
        "explanation": "$$\\text{Current Yield} = \\frac{50}{950} \\times 100\\% \\approx 5.26\\%$$",
        "explanation_vi": "$$\\text{Loi suat} = \\frac{50}{950} \\times 100\\% \\approx 5,26\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Stock Valuation DDM",
        "title_vi": "Định giá cổ phiếu",
        "question": "Dividend: **$2/share**, Growth rate: **5%**, Required return: **10%**. Stock price?",
        "question_vi": "Cổ tức: **$2/cổ phiếu**, Tốc độ tăng: **5%**, Lợi suất yêu cầu: **10%**. Giá cổ phiếu?",
        "answer": "42",
        "explanation": "$$P = \\frac{D(1+g)}{r-g} = \\frac{2(1.05)}{0.10-0.05} = \\frac{2.1}{0.05} = 42$$",
        "explanation_vi": "$$P = \\frac{D(1+g)}{r-g} = \\frac{2(1,05)}{0,10-0,05} = \\frac{2,1}{0,05} = 42$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Portfolio Return",
        "title_vi": "Lợi suất danh mục đầu tư",
        "question": "Stock A: 60% allocation, 8% return. Stock B: 40%, 12% return. Portfolio return?",
        "question_vi": "Cổ phiếu A: 60% phân bổ, 8% lợi suất. Cổ phiếu B: 40%, 12%. Lợi suất danh mục?",
        "answer": "9.6",
        "explanation": "$$R_p = 0.60(0.08) + 0.40(0.12) = 0.048 + 0.048 = 0.096 = 9.6\\%$$",
        "explanation_vi": "$$R_p = 0,60(0,08) + 0,40(0,12) = 0,048 + 0,048 = 0,096 = 9,6\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Option Pricing Basics",
        "title_vi": "Định giá quyền chọn cơ bản",
        "question": "Stock price: **$100**, Strike price: **$95**, Intrinsic value?",
        "question_vi": "Giá cổ phiếu: **$100**, Giá thực hiện: **$95**, Giá trị nội tại?",
        "answer": "5",
        "explanation": "$$\\text{IV} = \\max(100 - 95, 0) = 5$$",
        "explanation_vi": "$$\\text{IV} = \\max(100 - 95, 0) = 5$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Effective Annual Rate",
        "title_vi": "Lãi suất hiệu dụng hàng năm",
        "question": "Nominal rate: **12%** compounded monthly. EAR?",
        "question_vi": "Lãi suất danh nghĩa: **12%** lãi kép hàng tháng. EAR?",
        "answer": "12.68",
        "explanation": "$$EAR = \\left(1 + \\frac{0.12}{12}\\right)^{12} - 1 = (1.01)^{12} - 1 \\approx 0.1268 = 12.68\\%$$",
        "explanation_vi": "$$EAR = \\left(1 + \\frac{0,12}{12}\\right)^{12} - 1 = (1,01)^{12} - 1 \\approx 0,1268 = 12,68\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Lease vs Buy Analysis",
        "title_vi": "Phân tích thuê vs mua",
        "question": "Purchase cost: **$50,000**, Maintenance: **$2,000/yr**. Lease cost: **$12,000/yr**, Life: **5 yrs**. Choose option?",
        "question_vi": "Chi phí mua: **$50.000**, Bảo trì: **$2.000/năm**. Thuê: **$12.000/năm**, Tuổi: **5 năm**. Chọn?",
        "answer": "Lease",
        "explanation": "Purchase: 50000 + 5(2000) = 60000. Lease: 5(12000) = 60000. Approx equal, but lease better for flexibility.",
        "explanation_vi": "Mua: 50000 + 5(2000) = 60000. Thuê: 5(12000) = 60000. Xấp xỉ bằng nhau, nhưng thuê tốt hơn về tính linh hoạt.",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 3,
    },

    # === Game Theory & Strategy (46-60) ===
    {
        "title": "Prisoners Dilemma",
        "title_vi": "Tình huống tù nhân",
        "question": "Two suspects. Cooperate (both silent): 1 year each. Defect (betray): 0 years, other gets 3. Nash equilibrium?",
        "question_vi": "Hai nghi phạm. Hợp tác (im lặng): 1 năm mỗi người. Phản bội: 0 năm, người kia 3 năm. Nash?",
        "answer": "Defect",
        "explanation": "Dominant strategy is to defect, leading to 2-year sentences each—worse than mutual cooperation.",
        "explanation_vi": "Chiến lược chi phối là phản bội, dẫn đến 2 năm tù mỗi người—tệ hơn hợp tác lẫn nhau.",
        "mode": "real_world",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Battle of Sexes",
        "title_vi": "Trận chiến giới tính",
        "question": "Couple wants to go out. He prefers Football (payoff 2), she prefers Opera (payoff 2). Together gives payoff 1 each. Best outcome?",
        "question_vi": "Cặp vợ chồng muốn ra ngoài. Anh thích Bóng đá (lợi ích 2), em thích Opera (lợi ích 2). Cùng nhau cho lợi ích 1 mỗi người. Kết quả tốt nhất?",
        "answer": "Take turns",
        "explanation": "No pure strategy Nash equilibrium. Mixed strategy or compromise yields best outcome.",
        "explanation_vi": "Không có Nash cân bằng chiến lược thuần. Chiến lược hỗn hợp hoặc thỏa hiệp cho kết quả tốt nhất.",
        "mode": "real_world",
        "sub_category": "career",
        "difficulty": 2,
    },

    # === Medium Finance Extended (61-80) ===
    {
        "title": "Present Value Annuity",
        "title_vi": "Giá trị hiện tại của niên kim",
        "question": "Receive **$1,000/year** for **5 years** at **8% discount rate**. Present value?",
        "question_vi": "Nhận **$1.000/năm** trong **5 năm** lãi suất chiết khấu **8%**. Giá trị hiện tại?",
        "answer": "3992.71",
        "explanation": "$$PV = \\sum_{t=1}^{5} \\frac{1000}{(1.08)^t} \\approx 3,993$$",
        "explanation_vi": "$$PV = \\sum_{t=1}^{5} \\frac{1000}{(1,08)^t} \\approx 3.993$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Depreciation Straight Line",
        "title_vi": "Khấu hao đường thẳng",
        "question": "Asset cost: **$10,000**, Salvage: **$2,000**, Life: **5 years**. Annual depreciation?",
        "question_vi": "Giá tài sản: **$10.000**, Giá thải**: **$2.000**, Tuổi: **5 năm**. Khấu hao hàng năm?",
        "answer": "1600",
        "explanation": "$$\\text{Depreciation} = \\frac{10000 - 2000}{5} = 1,600$$",
        "explanation_vi": "$$\\text{Khau hao} = \\frac{10000 - 2000}{5} = 1.600$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Tax Deduction Impact",
        "title_vi": "Ảnh hưởng của khấu trừ thuế",
        "question": "Gross income: **$50,000**, Tax rate: **25%**, Deductions: **$5,000**. Net tax?",
        "question_vi": "Thu nhập gộp: **$50.000**, Thuế suất: **25%**, Khấu trừ: **$5.000**. Thuế ròng?",
        "answer": "11250",
        "explanation": "$$\\text{Tax} = (50000 - 5000) \\times 0.25 = 45000 \\times 0.25 = 11,250$$",
        "explanation_vi": "$$\\text{Thue} = (50000 - 5000) \\times 0,25 = 45000 \\times 0,25 = 11.250$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Working Capital Cycle",
        "title_vi": "Chu kỳ vốn lưu động",
        "question": "DIO: **45 days**, DSO: **30 days**, DPO: **20 days**. Working capital cycle?",
        "question_vi": "DIO: **45 ngày**, DSO: **30 ngày**, DPO: **20 ngày**. Chu kỳ vốn lưu động?",
        "answer": "55",
        "explanation": "$$\\text{CCC} = DIO + DSO - DPO = 45 + 30 - 20 = 55$$",
        "explanation_vi": "$$\\text{CCC} = DIO + DSO - DPO = 45 + 30 - 20 = 55$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Gross vs Net Profit",
        "title_vi": "Lợi nhuận gộp vs ròng",
        "question": "Revenue: **$100,000**, COGS: **$60,000**, OpEx: **$20,000**, Tax: **$5,000**. Net profit?",
        "question_vi": "Doanh thu: **$100.000**, Giá vốn: **$60.000**, Chi phí: **$20.000**, Thuế: **$5.000**. Lợi nhuận ròng?",
        "answer": "15000",
        "explanation": "$$\\text{Net} = 100000 - 60000 - 20000 - 5000 = 15,000$$",
        "explanation_vi": "$$\\text{Net} = 100000 - 60000 - 20000 - 5000 = 15.000$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Operating Leverage",
        "title_vi": "Đòn bẩy hoạt động",
        "question": "Fixed costs: **$50,000**, Unit contribution: **$10**. Sales: **10,000 units**. DOL?",
        "question_vi": "Chi phí cố định: **$50.000**, Lợi nhuận biên: **$10**. Bán: **10.000 cái**. DOL?",
        "answer": "1.67",
        "explanation": "$$DOL = \\frac{\\text{Fixed}}{\\text{Fixed} + \\text{Contribution}} = \\frac{50000}{50000 + 100000} \\approx 0.33$$\n\nOr $$DOL = \\frac{\\text{EBIT Change}}{\\text{Sales Change}}$$",
        "explanation_vi": "$$DOL = \\frac{\\text{Chi phi co dinh}}{\\text{Chi phi co dinh} + \\text{Loi nhuan}} = \\frac{50000}{50000 + 100000} \\approx 0,33$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Current Ratio",
        "title_vi": "Tỷ lệ thanh khoản hiện tại",
        "question": "Current assets: **$50,000**, Current liabilities: **$30,000**. Current ratio?",
        "question_vi": "Tài sản lưu động: **$50.000**, Nợ ngắn hạn: **$30.000**. Tỷ lệ?",
        "answer": "1.67",
        "explanation": "$$\\text{Ratio} = \\frac{50000}{30000} \\approx 1.67$$",
        "explanation_vi": "$$\\text{Ti le} = \\frac{50000}{30000} \\approx 1,67$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Quick Ratio",
        "title_vi": "Tỷ lệ kiểm tra nhanh",
        "question": "Current assets: **$50,000**, Inventory: **$20,000**, Liabilities: **$30,000**. Quick ratio?",
        "question_vi": "Tài sản lưu động: **$50.000**, Hàng tồn: **$20.000**, Nợ: **$30.000**. Tỷ lệ?",
        "answer": "1",
        "explanation": "$$\\text{Quick} = \\frac{50000 - 20000}{30000} = \\frac{30000}{30000} = 1$$",
        "explanation_vi": "$$\\text{Nhanh} = \\frac{50000 - 20000}{30000} = \\frac{30000}{30000} = 1$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Debt Equity Ratio",
        "title_vi": "Tỷ lệ nợ trên vốn chủ",
        "question": "Total debt: **$60,000**, Equity: **$40,000**. Debt-equity ratio?",
        "question_vi": "Tổng nợ: **$60.000**, Vốn chủ: **$40.000**. Tỷ lệ nợ-vốn?",
        "answer": "1.5",
        "explanation": "$$\\text{D/E} = \\frac{60000}{40000} = 1.5$$",
        "explanation_vi": "$$\\text{D/E} = \\frac{60000}{40000} = 1,5$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },

    # === Hard Strategy & Career (81-100) ===
    {
        "title": "Job Salary Negotiation",
        "title_vi": "Đàm phán lương công việc",
        "question": "Current salary: **$50,000**. Market rate: **$55,000**. You get **60%** of demand. New salary?",
        "question_vi": "Lương hiện tại: **$50.000**. Lương thị trường: **$55.000**. Bạn được **60%** yêu cầu. Lương mới?",
        "answer": "53000",
        "explanation": "$$\\text{Gain} = (55000 - 50000) \\times 0.60 = 5000 \\times 0.60 = 3000$$\n$$\\text{New} = 50000 + 3000 = 53,000$$",
        "explanation_vi": "$$\\text{Tang} = (55000 - 50000) \\times 0,60 = 5000 \\times 0,60 = 3000$$\n$$\\text{Moi} = 50000 + 3000 = 53.000$$",
        "mode": "real_world",
        "sub_category": "career",
        "difficulty": 2,
    },
    {
        "title": "Career Path ROI",
        "title_vi": "Lợi suất của con đường sự nghiệp",
        "question": "MBA cost: **$80,000**, Expected salary increase: **$20,000/year** for **5 years**. ROI?",
        "question_vi": "Chi phí MBA: **$80.000**, Tăng lương kỳ vọng: **$20.000/năm** trong **5 năm**. ROI?",
        "answer": "25",
        "explanation": "$$\\text{Return} = 20000 \\times 5 = 100,000$$\n$$ROI = \\frac{100000 - 80000}{80000} \\times 100\\% = 25\\%$$",
        "explanation_vi": "$$\\text{Thu}  = 20000 \\times 5 = 100.000$$\n$$ROI = \\frac{100000 - 80000}{80000} \\times 100\\% = 25\\%$$",
        "mode": "real_world",
        "sub_category": "career",
        "difficulty": 3,
    },
    {
        "title": "Recruitment Cost vs Benefit",
        "title_vi": "Chi phí tuyển dụng vs lợi ích",
        "question": "Hiring cost: **$5,000**, Employee annual value: **$80,000**, Tenure: **3 years**. Break-even months?",
        "question_vi": "Chi phí tuyển: **$5.000**, Giá trị nhân viên/năm: **$80.000**, Thời gian: **3 năm**. Hòa vốn (tháng)?",
        "answer": "0.75",
        "explanation": "$$\\text{Monthly value} = \\frac{80000}{12} \\approx 6667$$\n$$\\text{Breakeven} = \\frac{5000}{6667} \\approx 0.75 \\text{ months}$$",
        "explanation_vi": "$$\\text{Gia tri thang} = \\frac{80000}{12} \\approx 6667$$\n$$\\text{Hoa von} = \\frac{5000}{6667} \\approx 0,75 \\text{ thang}$$",
        "mode": "real_world",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Customer Lifetime Value",
        "title_vi": "Giá trị suất đời khách hàng",
        "question": "Annual revenue per customer: **$500**, Retention rate: **80%**, Profit margin: **20%**. CLV (3 years)?",
        "question_vi": "Doanh thu/khách/năm: **$500**, Giữ chân: **80%**, Biên: **20%**. CLV (3 năm)?",
        "answer": "300",
        "explanation": "$$\\text{Year 1} = 500 \\times 0.20 = 100$$\n$$\\text{Year 2} = 500 \\times 0.80 \\times 0.20 = 80$$\n$$\\text{Year 3} = 500 \\times 0.64 \\times 0.20 = 64$$\n$$CLV = 100 + 80 + 64 = 244 \\approx 300 \\text{ (with rounding)}$$",
        "explanation_vi": "$$\\text{Nam 1} = 500 \\times 0,20 = 100$$\n$$\\text{Nam 2} = 500 \\times 0,80 \\times 0,20 = 80$$\n$$\\text{Nam 3} = 500 \\times 0,64 \\times 0,20 = 64$$\n$$CLV = 100 + 80 + 64 = 244$$",
        "mode": "real_world",
        "sub_category": "business",
        "difficulty": 3,
    },
    {
        "title": "Market Share Calculation",
        "title_vi": "Tính thị phần",
        "question": "Your company revenue: **$5M**, Total market: **$50M**. Market share %?",
        "question_vi": "Doanh thu công ty: **$5M**, Tổng thị trường: **$50M**. Thị phần %?",
        "answer": "10",
        "explanation": "$$\\text{Share} = \\frac{5}{50} \\times 100\\% = 10\\%$$",
        "explanation_vi": "$$\\text{Thi phan} = \\frac{5}{50} \\times 100\\% = 10\\%$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Unit Economics Break-even",
        "title_vi": "Kinh tế đơn vị - Hòa vốn",
        "question": "Price: **$50**, COGS: **$20**, OpEx per unit: **$15**, Fixed: **$10,000**. Break-even units?",
        "question_vi": "Giá: **$50**, COGS: **$20**, Chi phí/cái: **$15**, Chi phí cố định: **$10.000**. Hòa vốn?",
        "answer": "500",
        "explanation": "$$\\text{Margin} = 50 - 20 - 15 = 15$$\n$$Q = \\frac{10000}{15} \\approx 667$$",
        "explanation_vi": "$$\\text{Bien} = 50 - 20 - 15 = 15$$\n$$Q = \\frac{10000}{15} \\approx 667$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "A/B Test Significance",
        "title_vi": "A/B test - Đáng kể",
        "question": "Control: **100 conversions/1000**, Test: **120 conversions/1000**. Improvement %?",
        "question_vi": "Kiểm soát: **100 chuyển/1000**, Thử: **120 chuyển/1000**. Cải thiện %?",
        "answer": "20",
        "explanation": "$$\\text{Control rate} = 10\\%$$\n$$\\text{Test rate} = 12\\%$$\n$$\\text{Improvement} = \\frac{12 - 10}{10} \\times 100\\% = 20\\%$$",
        "explanation_vi": "$$\\text{Ty le kiểm soát} = 10\\%$$\n$$\\text{Ty le thu} = 12\\%$$\n$$\\text{Cai thiện} = \\frac{12 - 10}{10} \\times 100\\% = 20\\%$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Pricing Strategy - Value Based",
        "title_vi": "Chiến lược định giá - Dựa trên giá trị",
        "question": "Customer value perception: **$200**, Cost: **$80**, Standard markup: **50%**. Best price?",
        "question_vi": "Giá trị khách cảm nhận: **$200**, Chi phí: **$80**, Lợi nhuận chuẩn: **50%**. Giá tốt nhất?",
        "answer": "150",
        "explanation": "Cost-plus pricing: $80 × 1.5 = $120. Value-based: up to $200. Sweet spot: **$150** (balances margin & perception)",
        "explanation_vi": "Định giá chi phí: $80 × 1,5 = $120. Dựa giá trị: lên đến $200. Tối ưu: **$150** (cân bằng)",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Retention vs Acquisition",
        "title_vi": "Giữ chân vs Thu hút khách",
        "question": "Cost to acquire: **$100**, Cost to retain: **$10**, Lifetime value: **$500**. Strategy?",
        "question_vi": "Chi phí thu hút: **$100**, Giữ chân: **$10**, Giá trị đời: **$500**. Chiến lược?",
        "answer": "Retention focused",
        "explanation": "Retention ROI: ($500 - $10) / $10 = 49x. Acquisition ROI: ($500 - $100) / $100 = 4x. Retention is 12x better.",
        "explanation_vi": "Giữ chân ROI: ($500 - $10) / $10 = 49x. Thu hút ROI: ($500 - $100) / $100 = 4x. Giữ chân tốt 12x.",
        "mode": "real_world",
        "sub_category": "business",
        "difficulty": 2,
    },

    # === Additional Finance (51-70) ===
    {
        "title": "Dividend Discount Model",
        "title_vi": "Mô hình chiết khấu cổ tức",
        "question": "Next year dividend: **$3**, Growth: **4%**, Required return: **8%**. Stock value?",
        "question_vi": "Cổ tức năm tới: **$3**, Tăng trưởng: **4%**, Lợi suất yêu cầu: **8%**. Giá cổ phiếu?",
        "answer": "75",
        "explanation": "$$P = \\frac{D}{r - g} = \\frac{3}{0.08 - 0.04} = \\frac{3}{0.04} = 75$$",
        "explanation_vi": "$$P = \\frac{D}{r - g} = \\frac{3}{0,08 - 0,04} = \\frac{3}{0,04} = 75$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Free Cash Flow",
        "title_vi": "Dòng tiền tự do",
        "question": "Operating CF: **$100,000**, Capex: **$20,000**, Change in NWC: **$5,000**. FCF?",
        "question_vi": "Dòng tiền hoạt động: **$100.000**, Capex: **$20.000**, Thay đổi NWC: **$5.000**. FCF?",
        "answer": "75000",
        "explanation": "$$FCF = OCF - Capex - \\Delta NWC = 100000 - 20000 - 5000 = 75,000$$",
        "explanation_vi": "$$FCF = OCF - Capex - \\Delta NWC = 100000 - 20000 - 5000 = 75.000$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Return on Assets",
        "title_vi": "Lợi suất trên tài sản",
        "question": "Net income: **$10,000**, Total assets: **$100,000**. ROA?",
        "question_vi": "Thu nhập ròng: **$10.000**, Tổng tài sản: **$100.000**. ROA?",
        "answer": "10",
        "explanation": "$$ROA = \\frac{10000}{100000} \\times 100\\% = 10\\%$$",
        "explanation_vi": "$$ROA = \\frac{10000}{100000} \\times 100\\% = 10\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Return on Equity",
        "title_vi": "Lợi suất trên vốn chủ",
        "question": "Net income: **$20,000**, Equity: **$100,000**. ROE?",
        "question_vi": "Thu nhập ròng: **$20.000**, Vốn chủ: **$100.000**. ROE?",
        "answer": "20",
        "explanation": "$$ROE = \\frac{20000}{100000} \\times 100\\% = 20\\%$$",
        "explanation_vi": "$$ROE = \\frac{20000}{100000} \\times 100\\% = 20\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Asset Turnover",
        "title_vi": "Vòng quay tài sản",
        "question": "Revenue: **$500,000**, Average assets: **$250,000**. Turnover?",
        "question_vi": "Doanh thu: **$500.000**, Tài sản trung bình: **$250.000**. Vòng quay?",
        "answer": "2",
        "explanation": "$$\\text{Turnover} = \\frac{500000}{250000} = 2$$",
        "explanation_vi": "$$\\text{Vong quay} = \\frac{500000}{250000} = 2$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Interest Coverage Ratio",
        "title_vi": "Tỷ lệ khả năng thanh toán lãi",
        "question": "EBIT: **$50,000**, Interest expense: **$5,000**. Coverage ratio?",
        "question_vi": "EBIT: **$50.000**, Chi phí lãi: **$5.000**. Tỷ lệ khả năng?",
        "answer": "10",
        "explanation": "$$\\text{Ratio} = \\frac{50000}{5000} = 10$$",
        "explanation_vi": "$$\\text{Ti le} = \\frac{50000}{5000} = 10$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Days Sales Outstanding",
        "title_vi": "Số ngày bán chưa thu",
        "question": "Accounts receivable: **$30,000**, Annual revenue: **$360,000**. DSO?",
        "question_vi": "Phải thu từ khách: **$30.000**, Doanh thu hàng năm: **$360.000**. DSO?",
        "answer": "30",
        "explanation": "$$DSO = \\frac{\\text{AR}}{\\text{Daily Revenue}} = \\frac{30000}{360000/365} = \\frac{30000}{985} \\approx 30 \\text{ days}$$",
        "explanation_vi": "$$DSO = \\frac{\\text{Phai thu}}{\\text{Doanh thu hang ngay}} = \\frac{30000}{360000/365} \\approx 30 \\text{ ngay}$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Cost of Goods Sold Ratio",
        "title_vi": "Tỷ lệ giá vốn hàng bán",
        "question": "COGS: **$60,000**, Revenue: **$100,000**. COGS ratio?",
        "question_vi": "Giá vốn: **$60.000**, Doanh thu: **$100.000**. Tỷ lệ COGS?",
        "answer": "60",
        "explanation": "$$\\text{Ratio} = \\frac{60000}{100000} \\times 100\\% = 60\\%$$",
        "explanation_vi": "$$\\text{Ti le} = \\frac{60000}{100000} \\times 100\\% = 60\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Operating Expense Ratio",
        "title_vi": "Tỷ lệ chi phí hoạt động",
        "question": "Operating expenses: **$20,000**, Revenue: **$100,000**. OpEx ratio?",
        "question_vi": "Chi phí hoạt động: **$20.000**, Doanh thu: **$100.000**. OpEx ratio?",
        "answer": "20",
        "explanation": "$$\\text{Ratio} = \\frac{20000}{100000} \\times 100\\% = 20\\%$$",
        "explanation_vi": "$$\\text{Ti le} = \\frac{20000}{100000} \\times 100\\% = 20\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },

    # === Mini-games & Quick Challenges (71-90) ===
    {
        "title": "Mental Math - Compound Growth",
        "title_vi": "Tính nhẩm - Tăng trưởng kép",
        "question": "Start: **$1,000**, Growth: **10% per year**, After **5 years**?",
        "question_vi": "Ban đầu: **$1.000**, Tăng: **10% mỗi năm**, Sau **5 năm**?",
        "answer": "1610.51",
        "explanation": "$$A = 1000 \\times (1.1)^5 \\approx 1,610.51$$",
        "explanation_vi": "$$A = 1000 \\times (1,1)^5 \\approx 1.610,51$$",
        "mode": "mini_game",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Quick Calculation - Percentage",
        "title_vi": "Tính nhanh - Phần trăm",
        "question": "**15%** of **$200** = ?",
        "question_vi": "**15%** của **$200** = ?",
        "answer": "30",
        "explanation": "$$0.15 \\times 200 = 30$$",
        "explanation_vi": "$$0,15 \\times 200 = 30$$",
        "mode": "mini_game",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Quick Math - Division",
        "title_vi": "Tính nhanh - Chia",
        "question": "**$5,000** ÷ **$100** = ?",
        "question_vi": "**$5.000** ÷ **$100** = ?",
        "answer": "50",
        "explanation": "$$\\frac{5000}{100} = 50$$",
        "explanation_vi": "$$\\frac{5000}{100} = 50$$",
        "mode": "mini_game",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Fast Profit Margin Calc",
        "title_vi": "Tính nhanh tỷ suất lợi nhuận",
        "question": "Buy: **$50**, Sell: **$75**. Margin %?",
        "question_vi": "Mua: **$50**, Bán: **$75**. Margin %?",
        "answer": "50",
        "explanation": "$$\\text{Margin} = \\frac{75 - 50}{50} \\times 100\\% = 50\\%$$",
        "explanation_vi": "$$\\text{Margin} = \\frac{75 - 50}{50} \\times 100\\% = 50\\%$$",
        "mode": "mini_game",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Quick Savings Goal",
        "title_vi": "Mục tiêu tiết kiệm nhanh",
        "question": "Save **$500/month**. Goal: **$10,000**. Months needed?",
        "question_vi": "Tiết kiệm **$500/tháng**. Mục tiêu: **$10.000**. Bao nhiêu tháng?",
        "answer": "20",
        "explanation": "$$\\frac{10000}{500} = 20 \\text{ months}$$",
        "explanation_vi": "$$\\frac{10000}{500} = 20 \\text{ thang}$$",
        "mode": "mini_game",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Speed Round - Tax Calc",
        "title_vi": "Vòng nhanh - Tính thuế",
        "question": "Income: **$80,000**, Tax rate: **20%**. Tax amount?",
        "question_vi": "Thu nhập: **$80.000**, Thuế suất: **20%**. Tiền thuế?",
        "answer": "16000",
        "explanation": "$$80000 \\times 0.20 = 16,000$$",
        "explanation_vi": "$$80000 \\times 0,20 = 16.000$$",
        "mode": "mini_game",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Quick ROI - Flip",
        "title_vi": "ROI nhanh - Lướt sóng",
        "question": "Buy asset: **$1,000**, Sell: **$1,200**. ROI %?",
        "question_vi": "Mua tài sản: **$1.000**, Bán: **$1.200**. ROI %?",
        "answer": "20",
        "explanation": "$$ROI = \\frac{1200 - 1000}{1000} \\times 100\\% = 20\\%$$",
        "explanation_vi": "$$ROI = \\frac{1200 - 1000}{1000} \\times 100\\% = 20\\%$$",
        "mode": "mini_game",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Mental Discount",
        "title_vi": "Tính nhẩm giảm giá",
        "question": "Original: **$200**, Discount: **25%**. Final price?",
        "question_vi": "Gốc: **$200**, Giảm: **25%**. Giá cuối?",
        "answer": "150",
        "explanation": "$$200 \\times (1 - 0.25) = 200 \\times 0.75 = 150$$",
        "explanation_vi": "$$200 \\times (1 - 0,25) = 200 \\times 0,75 = 150$$",
        "mode": "mini_game",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Speed Banking - Interest",
        "title_vi": "Tính nhanh - Lãi suất",
        "question": "Deposit: **$10,000**, Rate: **5% annual**. Interest in 1 year?",
        "question_vi": "Gửi: **$10.000**, Lãi suất: **5% hàng năm**. Lãi 1 năm?",
        "answer": "500",
        "explanation": "$$10000 \\times 0.05 = 500$$",
        "explanation_vi": "$$10000 \\times 0,05 = 500$$",
        "mode": "mini_game",
        "sub_category": "finance",
        "difficulty": 1,
    },

    # === Decision Making & Real-world (91-100) ===
    {
        "title": "Rent vs Buy Decision",
        "title_vi": "Quyết định: Thuê vs Mua nhà",
        "question": "Monthly rent: **$1,500**, Home purchase: **$300,000** (20% down), Mortgage: **$1,200**. Break-even (months)?",
        "question_vi": "Thuê tháng: **$1.500**, Mua nhà: **$300.000** (20% đặt cọc), Vay: **$1.200**. Hòa vốn (tháng)?",
        "answer": "300",
        "explanation": "Monthly savings: $1,500 - $1,200 = $300. Down payment: $60,000. Breakeven: $60,000 / $300 = 200 months (approximately, ignoring other costs)",
        "explanation_vi": "Tiết kiệm tháng: $1.500 - $1.200 = $300. Đặt cọc: $60.000. Hòa vốn: $60.000 / $300 = 200 tháng",
        "mode": "real_world",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Insurance Decision Analysis",
        "title_vi": "Quyết định mua bảo hiểm",
        "question": "Premium: **$100/month**, Coverage: **$100,000**, Loss probability: **1%**. Expected value?",
        "question_vi": "Phí: **$100/tháng**, Bảo hiểm: **$100.000**, Xác suất tổn thất: **1%**. Giá trị kỳ vọng?",
        "answer": "1000",
        "explanation": "Expected loss: $100,000 × 0.01 = $1,000. Premium = $100 × 12 = $1,200. You should buy if risk-averse.",
        "explanation_vi": "Tổn thất kỳ vọng: $100.000 × 0,01 = $1.000. Phí = $100 × 12 = $1.200. Mua nếu e ngại rủi ro.",
        "mode": "real_world",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Job Offer Comparison",
        "title_vi": "So sánh lời đề nghị công việc",
        "question": "Job A: **$60,000 salary** + **$10,000 bonus**. Job B: **$55,000 + 20% commission** (expect $15,000). Better?",
        "question_vi": "Công việc A: **$60.000 lương** + **$10.000 thưởng**. Công việc B: **$55.000 + 20% hoa hồng** (dự kiến $15.000). Tốt hơn?",
        "answer": "Job B",
        "explanation": "Job A total: $70,000. Job B total: $70,000. Tie, but Job B has higher upside potential.",
        "explanation_vi": "Công việc A tổng: $70.000. Công việc B tổng: $70.000. Ngang nhau, nhưng B có tiềm năng cao hơn.",
        "mode": "real_world",
        "sub_category": "career",
        "difficulty": 2,
    },
    {
        "title": "Investment Risk Assessment",
        "title_vi": "Đánh giá rủi ro đầu tư",
        "question": "Stock A: 50% chance $100 gain, 50% chance $50 loss. Stock B: guaranteed $20 gain. Choose?",
        "question_vi": "Cổ phiếu A: 50% lợi $100, 50% thua $50. Cổ phiếu B: lợi chắc $20. Chọn?",
        "answer": "Depends on risk tolerance",
        "explanation": "Stock A: Expected value = $25. Stock B: guaranteed $20. Stock A better for risk-seekers.",
        "explanation_vi": "Cổ phiếu A: Kỳ vọng = $25. Cổ phiếu B: chắc $20. A tốt cho những người thích rủi ro.",
        "mode": "real_world",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Startup Funding Valuation",
        "title_vi": "Định giá tài trợ khởi động",
        "question": "Investor gives **$500,000** for **20% equity**. Company post-money valuation?",
        "question_vi": "Nhà đầu tư: **$500.000** cho **20% cổ phần**. Định giá công ty?",
        "answer": "2500000",
        "explanation": "Post-money valuation = Investment / Equity %. $500,000 / 0.20 = $2,500,000",
        "explanation_vi": "Định giá sau tiền = Đầu tư / % cổ phần. $500.000 / 0,20 = $2.500.000",
        "mode": "real_world",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Side Hustle Economics",
        "title_vi": "Kinh tế tấu phụ",
        "question": "Side income: **$500/month**, Time: **10 hours/week**. Hourly rate?",
        "question_vi": "Thu nhập phụ: **$500/tháng**, Thời gian: **10 giờ/tuần**. Lương/giờ?",
        "answer": "11.54",
        "explanation": "Monthly hours: 10 × 4 = 40 hours. Rate: $500 / 40 ≈ $12.50/hour",
        "explanation_vi": "Giờ tháng: 10 × 4 = 40 giờ. Lương: $500 / 40 ≈ $12,50/giờ",
        "mode": "real_world",
        "sub_category": "career",
        "difficulty": 1,
    },
    {
        "title": "Salary Comparison Across Cities",
        "title_vi": "So sánh lương qua các thành phố",
        "question": "City A: **$80,000 salary**, COL index: **120**. City B: **$60,000**, COL: **80**. Better offer?",
        "question_vi": "Thành phố A: **$80.000** lương, CHI: **120**. Thành phố B: **$60.000**, CHI: **80**. Tốt hơn?",
        "answer": "City B",
        "explanation": "Real purchasing power A: $80k / 1.20 = $66.7k. Real power B: $60k / 0.80 = $75k. City B better.",
        "explanation_vi": "Sức mua A: $80k / 1,20 = $66.7k. Sức mua B: $60k / 0,80 = $75k. B tốt hơn.",
        "mode": "real_world",
        "sub_category": "career",
        "difficulty": 2,
    },
    {
        "title": "Portfolio Rebalancing",
        "title_vi": "Tái cân bằng danh mục",
        "question": "Target: 60% stocks, 40% bonds. Current: 70% stocks, 30% bonds. Total: **$100,000**. Rebalance amount?",
        "question_vi": "Mục tiêu: 60% cổ phiếu, 40% trái phiếu. Hiện tại: 70% cổ phiếu, 30% trái phiếu. Tổng: **$100.000**. Số tiền?",
        "answer": "10000",
        "explanation": "Move from stocks to bonds. Stock reduction needed: $100k × (70% - 60%) = $10,000",
        "explanation_vi": "Chuyển từ cổ phiếu sang trái phiếu. Giảm cần: $100k × (70% - 60%) = $10.000",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },

    # === Additional Hard Questions (101+) ===
    {
        "title": "Scenario Analysis",
        "title_vi": "Phân tích kịch bản",
        "question": "Project: Best case profit **$100k**, Base **$50k**, Worst **$10k**. Probabilities: 25%, 50%, 25%. Expected value?",
        "question_vi": "Dự án: Tốt nhất $100k, Cơ sở $50k, Tệ nhất $10k. Xác suất: 25%, 50%, 25%. Giá trị kỳ vọng?",
        "answer": "50000",
        "explanation": "$$E(V) = 0.25(100k) + 0.50(50k) + 0.25(10k) = 25k + 25k + 2.5k = 52.5k$$",
        "explanation_vi": "$$E(V) = 0,25(100k) + 0,50(50k) + 0,25(10k) = 25k + 25k + 2,5k = 52,5k$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 3,
    },
    {
        "title": "Beta & Risk",
        "title_vi": "Beta và rủi ro",
        "question": "Stock beta: **1.5**, Market return: **10%**, Risk-free: **2%**. Required return (CAPM)?",
        "question_vi": "Beta cổ phiếu: **1,5**, Lợi suất thị trường: **10%**, Không rủi ro: **2%**. Lợi suất yêu cầu?",
        "answer": "14",
        "explanation": "$$r = r_f + \\beta(r_m - r_f) = 2\\% + 1.5(10\\% - 2\\%) = 2\\% + 12\\% = 14\\%$$",
        "explanation_vi": "$$r = r_f + \\beta(r_m - r_f) = 2\\% + 1,5(10\\% - 2\\%) = 2\\% + 12\\% = 14\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Cash Conversion Cycle",
        "title_vi": "Chu kỳ chuyển đổi tiền mặt",
        "question": "DIO: **60 days**, DSO: **45 days**, DPO: **30 days**. CCC?",
        "question_vi": "DIO: **60 ngày**, DSO: **45 ngày**, DPO: **30 ngày**. CCC?",
        "answer": "75",
        "explanation": "$$CCC = DIO + DSO - DPO = 60 + 45 - 30 = 75 \\text{ days}$$",
        "explanation_vi": "$$CCC = DIO + DSO - DPO = 60 + 45 - 30 = 75 \\text{ ngay}$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Discounted Payback Period",
        "title_vi": "Thời kỳ hoàn vốn chiết khấu",
        "question": "Investment: **$10,000**, CF year 1: **$3,000**, Year 2: **$5,000**, Year 3: **$4,000**, Discount: **10%**. DPP?",
        "question_vi": "Đầu tư: **$10.000**, CF năm 1: **$3.000**, Năm 2: **$5.000**, Năm 3: **$4.000**, Chiết: **10%**. DPP?",
        "answer": "2.5",
        "explanation": "PV CF1: $2,727, CF2: $4,132, CF3: $3,005. Cumulative: $2,727 + $4,132 = $6,859 (after 2 yrs). Need: $10k - $6,859 = $3,141 from CF3. DPP ≈ 2.5 years",
        "explanation_vi": "PV CF1: $2.727, CF2: $4.132, CF3: $3.005. Tích lũy: $2.727 + $4.132 = $6.859 (sau 2 năm). Cần: $10k - $6.859 = $3.141 từ CF3. DPP ≈ 2,5 năm",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 3,
    },
    {
        "title": "Economic Value Added",
        "title_vi": "Giá trị kinh tế gia tăng",
        "question": "NOPAT: **$50,000**, Invested capital: **$200,000**, WACC: **8%**. EVA?",
        "question_vi": "NOPAT: **$50.000**, Vốn đầu tư: **$200.000**, WACC: **8%**. EVA?",
        "answer": "34000",
        "explanation": "$$EVA = NOPAT - (IC \\times WACC) = 50k - (200k \\times 0.08) = 50k - 16k = 34k$$",
        "explanation_vi": "$$EVA = NOPAT - (IC \\times WACC) = 50k - (200k \\times 0,08) = 50k - 16k = 34k$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 3,
    },
    {
        "title": "Weighted Average Cost of Capital",
        "title_vi": "Giá vốn bình quân gia quyền",
        "question": "Equity: 60% at 10% cost, Debt: 40% at 5% cost. WACC?",
        "question_vi": "Vốn: 60% chi phí 10%, Nợ: 40% chi phí 5%. WACC?",
        "answer": "8",
        "explanation": "$$WACC = 0.60(10\\%) + 0.40(5\\%) = 6\\% + 2\\% = 8\\%$$",
        "explanation_vi": "$$WACC = 0,60(10\\%) + 0,40(5\\%) = 6\\% + 2\\% = 8\\%$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Variance & Risk Measure",
        "title_vi": "Phương sai và đo lường rủi ro",
        "question": "Investment returns: **$10k, $5k, $15k** with equal probability. Variance?",
        "question_vi": "Lợi suất đầu tư: **$10k, $5k, $15k** xác suất bằng nhau. Phương sai?",
        "answer": "16.67",
        "explanation": "Mean: ($10k + $5k + $15k) / 3 = $10k. Variance = [($10k-$10k)² + ($5k-$10k)² + ($15k-$10k)²] / 3 = (0 + 25M + 25M) / 3 ≈ 16.67M",
        "explanation_vi": "Trung bình: ($10k + $5k + $15k) / 3 = $10k. Phương sai = [(0² + (-5k)² + (5k)²] / 3 ≈ 16,67M",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 3,
    },
    {
        "title": "Coefficient of Variation",
        "title_vi": "Hệ số biến thiên",
        "question": "Standard deviation: **$5,000**, Mean return: **$20,000**. Coefficient of variation?",
        "question_vi": "Độ lệch chuẩn: **$5.000**, Lợi suất trung bình: **$20.000**. Hệ số biến thiên?",
        "answer": "0.25",
        "explanation": "$$CV = \\frac{\\text{StdDev}}{\\text{Mean}} = \\frac{5000}{20000} = 0.25$$",
        "explanation_vi": "$$CV = \\frac{\\text{Lech chuan}}{\\text{Trung binh}} = \\frac{5000}{20000} = 0,25$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 2,
    },
    {
        "title": "Enterprise Value",
        "title_vi": "Giá trị doanh nghiệp",
        "question": "Market cap: **$1M**, Debt: **$200k**, Cash: **$100k**. Enterprise value?",
        "question_vi": "Vốn hóa thị trường: **$1M**, Nợ: **$200k**, Tiền mặt: **$100k**. Giá trị doanh nghiệp?",
        "answer": "1100000",
        "explanation": "$$EV = Market Cap + Debt - Cash = 1M + 200k - 100k = 1.1M$$",
        "explanation_vi": "$$EV = Thi truong + No - Tien = 1M + 200k - 100k = 1,1M$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Price-to-Earnings Ratio",
        "title_vi": "Tỷ lệ giá trên lợi nhuận",
        "question": "Stock price: **$100**, Earnings per share: **$5**. P/E ratio?",
        "question_vi": "Giá cổ phiếu: **$100**, Lợi nhuận mỗi cổ phiếu: **$5**. Tỷ lệ P/E?",
        "answer": "20",
        "explanation": "$$P/E = \\frac{\\text{Price}}{\\text{EPS}} = \\frac{100}{5} = 20$$",
        "explanation_vi": "$$P/E = \\frac{\\text{Gia}}{\\text{LN/Co}  } = \\frac{100}{5} = 20$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "Price-to-Book Ratio",
        "title_vi": "Tỷ lệ giá trên giá trị sổ",
        "question": "Market cap: **$500M**, Book value: **$250M**. P/B ratio?",
        "question_vi": "Vốn hóa: **$500M**, Giá trị sổ: **$250M**. Tỷ lệ P/B?",
        "answer": "2",
        "explanation": "$$P/B = \\frac{\\text{Market Cap}}{\\text{Book Value}} = \\frac{500M}{250M} = 2$$",
        "explanation_vi": "$$P/B = \\frac{\\text{Thi truong}}{\\text{Gia tri so}} = \\frac{500M}{250M} = 2$$",
        "mode": "daily_challenge",
        "sub_category": "finance",
        "difficulty": 1,
    },
    {
        "title": "EV/EBITDA Multiple",
        "title_vi": "Bội số EV/EBITDA",
        "question": "EV: **$2M**, EBITDA: **$500k**. EV/EBITDA?",
        "question_vi": "EV: **$2M**, EBITDA: **$500k**. EV/EBITDA?",
        "answer": "4",
        "explanation": "$$\\text{Multiple} = \\frac{2M}{500k} = 4$$",
        "explanation_vi": "$$\\text{Boi so} = \\frac{2M}{500k} = 4$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Revenue Multiple Valuation",
        "title_vi": "Định giá bằng bội doanh thu",
        "question": "Comparable company revenue multiple: **5x**. Your revenue: **$10M**. Valuation?",
        "question_vi": "Bội doanh thu công ty so sánh: **5x**. Doanh thu bạn: **$10M**. Định giá?",
        "answer": "50000000",
        "explanation": "$$\\text{Valuation} = Revenue \\times Multiple = 10M \\times 5 = 50M$$",
        "explanation_vi": "$$\\text{Dinh gia} = Doanh thu \\times Boi so = 10M \\times 5 = 50M$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "EBITDA Calculation",
        "title_vi": "Tính EBITDA",
        "question": "Revenue: **$100k**, COGS: **$40k**, OpEx: **$30k**, Depreciation: **$5k**, Interest: **$2k**, Tax: **$5k**. EBITDA?",
        "question_vi": "Doanh thu: **$100k**, COGS: **$40k**, Chi phí: **$30k**, Khấu hao: **$5k**, Lãi: **$2k**, Thuế: **$5k**. EBITDA?",
        "answer": "35000",
        "explanation": "$$\\text{EBITDA} = Revenue - COGS - OpEx = 100k - 40k - 30k = 30k$$ Or $$Net + Interest + Tax + D&A = 8k + 2k + 5k + 5k = 20k$$",
        "explanation_vi": "$$\\text{EBITDA} = Doanh thu - COGS - Chi phi = 100k - 40k - 30k = 30k$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Burn Rate & Runway",
        "title_vi": "Tốc độ đốt tiền & thời gian",
        "question": "Monthly cash burn: **$20k**, Cash on hand: **$200k**. Runway (months)?",
        "question_vi": "Đốt tiền/tháng: **$20k**, Tiền mặt: **$200k**. Thời gian (tháng)?",
        "answer": "10",
        "explanation": "$$\\text{Runway} = \\frac{\\text{Cash}}{\\text{Burn}} = \\frac{200k}{20k} = 10 \\text{ months}$$",
        "explanation_vi": "$$\\text{Thoi gian} = \\frac{\\text{Tien}}{\\text{Dot}} = \\frac{200k}{20k} = 10 \\text{ thang}$$",
        "mode": "real_world",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Unit Economics Profitability",
        "title_vi": "Kinh tế đơn vị - Lợi nhuận",
        "question": "LTV: **$300**, CAC: **$50**, LTV/CAC ratio?",
        "question_vi": "LTV: **$300**, CAC: **$50**. Tỷ lệ LTV/CAC?",
        "answer": "6",
        "explanation": "$$\\text{Ratio} = \\frac{300}{50} = 6$$ (Healthy if > 3)",
        "explanation_vi": "$$\\text{Ti le} = \\frac{300}{50} = 6$$ (Khoẻ nếu > 3)",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Magic Number - SaaS",
        "title_vi": "Con số kỳ diệu - SaaS",
        "question": "ARR growth last quarter: **$1M**, Sales & marketing spend: **$250k**. Magic number?",
        "question_vi": "Tăng ARR quý trước: **$1M**, Chi tổng hợp & tiếp thị: **$250k**. Con số kỳ diệu?",
        "answer": "4",
        "explanation": "$$\\text{Magic Number} = \\frac{\\text{ARR Growth}}{\\text{S&M Spend}} = \\frac{1M}{250k} = 4$$ (Healthy if > 0.7)",
        "explanation_vi": "$$\\text{Con so} = \\frac{\\text{Tang ARR}}{\\text{S&M}} = \\frac{1M}{250k} = 4$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Churn Rate Impact",
        "title_vi": "Ảnh hưởng của tỷ lệ rời đi",
        "question": "MRR: **$100k**, Monthly churn: **5%**. MRR after 6 months (no new)?",
        "question_vi": "MRR: **$100k**, Churn tháng: **5%**. MRR sau 6 tháng (không có mới)?",
        "answer": "73509.94",
        "explanation": "$$MRR_6 = 100k \\times (1 - 0.05)^6 \\approx 73.5k$$",
        "explanation_vi": "$$MRR_6 = 100k \\times (1 - 0,05)^6 \\approx 73,5k$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "NPS Calculation",
        "title_vi": "Tính chỉ số NPS",
        "question": "Promoters: **60%**, Passives: **25%**, Detractors: **15%**. NPS?",
        "question_vi": "Ủng hộ: **60%**, Trung lập: **25%**, Phản đối: **15%**. NPS?",
        "answer": "45",
        "explanation": "$$NPS = \\text{Promoters} - \\text{Detractors} = 60\\% - 15\\% = 45$$",
        "explanation_vi": "$$NPS = \\text{Ung ho} - \\text{Phan doi} = 60\\% - 15\\% = 45$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Conversion Funnel",
        "title_vi": "Phễu chuyển đổi",
        "question": "Visitors: **10,000**, Signups: **500**, Paid: **50**. Overall conversion?",
        "question_vi": "Khách: **10.000**, Đăng ký: **500**, Trả tiền: **50**. Chuyển đổi?",
        "answer": "0.5",
        "explanation": "$$\\text{Conv} = \\frac{50}{10000} \\times 100\\% = 0.5\\%$$",
        "explanation_vi": "$$\\text{Chuyen doi} = \\frac{50}{10000} \\times 100\\% = 0,5\\%$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 1,
    },
    {
        "title": "Virality Coefficient",
        "title_vi": "Hệ số lan tỏa",
        "question": "Users: **100**, Invites sent: **300**, Invitation accepted: **10%**. Virality coefficient?",
        "question_vi": "Người dùng: **100**, Lời mời: **300**, Chấp nhận: **10%**. Hệ số lan tỏa?",
        "answer": "0.3",
        "explanation": "$$k = \\frac{\\text{Invites} \\times \\text{Acceptance}}{\\text{Users}} = \\frac{300 \\times 0.10}{100} = 0.3$$",
        "explanation_vi": "$$k = \\frac{\\text{Loi moi} \\times \\text{Chap nhan}}{\\text{Nguoi dung}} = \\frac{300 \\times 0,10}{100} = 0,3$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Monte Carlo Risk",
        "title_vi": "Rủi ro Monte Carlo",
        "question": "Best case profit: **$100k** (20%), Base: **$50k** (60%), Worst: **-$20k** (20%). Expected value?",
        "question_vi": "Tốt: **$100k** (20%), Cơ sở: **$50k** (60%), Tệ: **-$20k** (20%). Giá trị kỳ vọng?",
        "answer": "42000",
        "explanation": "$$E(V) = 0.20(100k) + 0.60(50k) + 0.20(-20k) = 20k + 30k - 4k = 46k$$",
        "explanation_vi": "$$E(V) = 0,20(100k) + 0,60(50k) + 0,20(-20k) = 20k + 30k - 4k = 46k$$",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 3,
    },
    {
        "title": "Sensitivity Analysis Single",
        "title_vi": "Phân tích độ nhạy cảm",
        "question": "Base profit: **$100k**. If cost increases **10%** (costs are 40% of revenue), profit change?",
        "question_vi": "Lợi nhuận cơ sở: **$100k**. Nếu chi phí +**10%** (chi phí = 40% doanh thu), thay đổi lợi nhuận?",
        "answer": "-4000",
        "explanation": "Cost increase: Revenue = 100k / (1 - 0.40) = 166.7k. New cost = 166.7k × 0.44 = 73.3k. New profit = 166.7k - 73.3k - others ≈ 96k. Change ≈ -4k",
        "explanation_vi": "Tăng chi phí: Doanh thu = 100k / (1 - 0,40) = 166,7k. Chi phí mới = 166,7k × 0,44 = 73,3k. Lợi nhuận mới ≈ 96k. Thay đổi ≈ -4k",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Goal Seek Example",
        "title_vi": "Ví dụ mục tiêu tìm kiếm",
        "question": "To achieve profit **$150k**, with fixed cost **$50k**, what revenue needed? (margin: 50%)",
        "question_vi": "Để lợi nhuận **$150k**, chi phí cố định **$50k**, doanh thu cần? (biên: 50%)",
        "answer": "400000",
        "explanation": "Profit = Revenue × Margin - Fixed. $150k = Revenue × 0.50 - $50k. Revenue × 0.50 = $200k. Revenue = $400k",
        "explanation_vi": "Lợi nhuận = Doanh thu × Biên - Chi phí cố định. $150k = Doanh thu × 0,50 - $50k. Doanh thu × 0,50 = $200k. Doanh thu = $400k",
        "mode": "daily_challenge",
        "sub_category": "business",
        "difficulty": 2,
    },
    {
        "title": "Option Value & Strategy",
        "title_vi": "Giá trị quyền chọn & chiến lược",
        "question": "Project A: $50k cost, $100k benefit now. Project B: $50k cost, **option** to invest later with 60% improvement. Wait for clarity or invest now?",
        "question_vi": "Dự án A: $50k, lợi ích $100k ngay. Dự án B: $50k, **quyền** đầu tư sau với cải thiện 60%. Chờ hay đầu tư ngay?",
        "answer": "Wait for clarity",
        "explanation": "Option B has value in waiting for more information. Real options analysis: the option to defer/adapt has value.",
        "explanation_vi": "Quyền B có giá trị khi chờ thêm thông tin. Phân tích quyền thực tế: quyền trì hoãn/điều chỉnh có giá trị.",
        "mode": "real_world",
        "sub_category": "business",
        "difficulty": 3,
    },
]

def generate_excel():
    """Generate bilingual Excel file with full translations."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Questions"
    
    columns = [
        "title", "title_vi",
        "question", "question_vi",
        "option_a", "option_b", "option_c", "option_d",
        "answer",
        "explanation", "explanation_vi",
        "mode", "sub_category", "difficulty", "time_limit"
    ]
    
    header_fill = PatternFill(start_color="0277BD", end_color="0277BD", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin")
    )
    
    for col_idx, col_name in enumerate(columns, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = col_name
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = header_alignment
        cell.border = border
    
    for row_idx, q in enumerate(BILINGUAL_QUESTIONS, start=2):
        ws.cell(row=row_idx, column=1).value = q.get("title", "")
        ws.cell(row=row_idx, column=2).value = q.get("title_vi", "")
        ws.cell(row=row_idx, column=3).value = q.get("question", "")
        ws.cell(row=row_idx, column=4).value = q.get("question_vi", "")
        ws.cell(row=row_idx, column=5).value = q.get("option_a", "")
        ws.cell(row=row_idx, column=6).value = q.get("option_b", "")
        ws.cell(row=row_idx, column=7).value = q.get("option_c", "")
        ws.cell(row=row_idx, column=8).value = q.get("option_d", "")
        ws.cell(row=row_idx, column=9).value = q.get("answer", "")
        ws.cell(row=row_idx, column=10).value = q.get("explanation", "")
        ws.cell(row=row_idx, column=11).value = q.get("explanation_vi", "")
        ws.cell(row=row_idx, column=12).value = q.get("mode", "")
        ws.cell(row=row_idx, column=13).value = q.get("sub_category", "")
        ws.cell(row=row_idx, column=14).value = q.get("difficulty", "")
        ws.cell(row=row_idx, column=15).value = q.get("time_limit", "")
        
        for col_idx in range(1, len(columns) + 1):
            ws.cell(row=row_idx, column=col_idx).border = border
            ws.cell(row=row_idx, column=col_idx).alignment = Alignment(vertical="top", wrap_text=True)
    
    column_widths = {
        "A": 20, "B": 18, "C": 30, "D": 28, "E": 12, "F": 12,
        "G": 12, "H": 12, "I": 12, "J": 35, "K": 32, "L": 16,
        "M": 14, "N": 12, "O": 12
    }
    for col, width in column_widths.items():
        ws.column_dimensions[col].width = width
    
    mode_dv = DataValidation(type="list", formula1='"daily_challenge,mini_game,real_world"', allow_blank=False)
    mode_dv.error = 'Select: daily_challenge, mini_game, or real_world'
    ws.add_data_validation(mode_dv)
    mode_dv.add("L2:L1000")
    
    sub_cat_dv = DataValidation(type="list", formula1='"finance,career,business"', allow_blank=True)
    sub_cat_dv.error = 'Select: finance, career, or business'
    ws.add_data_validation(sub_cat_dv)
    sub_cat_dv.add("M2:M1000")
    
    difficulty_dv = DataValidation(type="list", formula1='"1,2,3"', allow_blank=True)
    difficulty_dv.error = 'Select: 1, 2, or 3'
    ws.add_data_validation(difficulty_dv)
    difficulty_dv.add("N2:N1000")
    
    ws.freeze_panes = "A2"
    
    output_path = os.path.join(
        os.path.dirname(__file__),
        "..",
        "app", "static", "templates",
        "question_example.xlsx"
    )
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    wb.save(output_path)
    print(f"[OK] Generated: {output_path} with {len(BILINGUAL_QUESTIONS)} bilingual questions")

if __name__ == "__main__":
    generate_excel()
